### ISSUE TITLE
Simple example

### ISSUE THREAD

**Issue by shersoni610** [webcamoid/akvirtualcamera#13]
Hello,

I want to pass OpenCV to a virtual webcamera. Is there a simple example to demonstrate how
it can be done using this software?

Thanks

**Comment by hipersayanX** [comment]
There will be no documentation until the project is finished, because there some bugs that needs to be solved before. But you can guide your self with some examples I've posted [here](https://github.com/webcamoid/akvirtualcamera/issues/9#issuecomment-768008512) and [here](https://github.com/webcamoid/akvirtualcamera/issues/3).
The management and communication with the virtual camera is made entirely from the manager, no linking is required with any library.

**Comment by shersoni610** [comment]
I want to capture images from OpenCV, pass it to VirtualCamera.  The end user should be able to play the content with ffplay or
vlc software. is is possible to do it?

**Comment by hipersayanX** [comment]
@shersoni610 yes, read my previous message and check the links I've posted.

**Comment by hipersayanX** [comment]
I've updated the wiki and  added some C examples for [Mac](https://github.com/webcamoid/akvirtualcamera/blob/master/share/examples/output_mac.c) and [Windows](https://github.com/webcamoid/akvirtualcamera/blob/master/share/examples/output_windows.c).
