### ISSUE TITLE
[Question] Outputting OBS to akvirtualcam MacOS

### ISSUE THREAD

**Issue by asher-the-thrasher** [webcamoid/akvirtualcamera#33]
# Questinons and other matters?

I am trying to output OBS to the akvirtualcam so I can have another virtual camera for obs. I am having trouble figuring out how to do `ffmpeg -i video.webm -pix_fmt rgb24 -f rawvideo - | AkVCamManager stream AkVCamVideoDevice0 RGB24 480 360` in OBS ffmpeg output settings. 

I am on MacOS Monterey and obs 27.1.3 and have downloaded the most recent version of akvirtualcamera. 

Sorry if this is the wrong way/place to post this kind of question, please direct me to the proper place if so.

**Comment by hipersayanX** [comment]
Maybe a solution would be [streaming with OBS locally](https://www.youtube.com/watch?v=18oGqNH9zmo), then using the stream URL as an input for FFmpeg (instead of the video file), and all the rest being the same.
A much better solution would be [writing an OBS plugin](https://obsproject.com/docs/plugins.html) for the virtual camera, [here](https://github.com/webcamoid/akvirtualcamera/tree/master/share/examples) you can find some code examples.
