### ISSUE TITLE
Stream bitmap ( single frame image ) to the virtual device

### ISSUE THREAD

**Issue by hesa2020** [webcamoid/akvirtualcamera#47]
Hello I looked around and tried a few things.
if I run manually the command it works:

"C:\ffmpeg\bin\ffmpeg.exe" -loop 1 -framerate 1 -i temp.jpg -r 1 -pix_fmt rgb24 -f rawvideo - | "C:\Program Files\AkVirtualCamera\x64\AkVCamManager.exe" stream MyFakeCamera0 RGB24 640 480

In my c# app this is what I do:

```
cameraProcess= new Process();
ProcessStartInfo startInfo = new System.Diagnostics.ProcessStartInfo();
startInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden;
startInfo.FileName = "C:\\Program Files\\AkVirtualCamera\\x64\\AkVCamManager.exe";
startInfo.Arguments = "stream MyFakeCamera0 RGB24 640 480";
startInfo.RedirectStandardError = true;
startInfo.RedirectStandardInput = true;
startInfo.RedirectStandardOutput = true;
startInfo.UseShellExecute = false;
startInfo.CreateNoWindow = true;
cameraProcess.StartInfo = startInfo;
cameraProcess.Start();
```
            
And then to send my image to the camera:
```
Task.Factory.StartNew(async () =>
{
    while(true)
    {
        try
        {
            MemoryStream outputStream = new MemoryStream();
            await FFMpegArguments
            .FromFileInput(Path.Combine(Environment.CurrentDirectory, "temp.jpg"))
            .OutputToPipe(new StreamPipeSink(outputStream), options => options
                .WithFrameOutputCount(1)
                .WithFramerate(1)
                .ForcePixelFormat("rgb24")
                .ForceFormat("rawvideo"))
            .ProcessAsynchronously();
            var data = outputStream.ToArray();
            cameraProcess.StandardInput.BaseStream.Write(data, 0, data.Length);
        }
        catch(Exception ex)
        {
            Console.WriteLine(ex.Message);
        }
        await Task.Delay(1000 / 30);
    }
});
```
            
However I really dislike the idea of starting 33 process per second to stream an image.

Then I see my temp.jpg being shown as the virtual camera.

What would be the easiest way to get my bitmap as rgb24 format ( I have no clue how this format actually works ) and write it to the device. ( without using ffmpeg )

**Comment by hipersayanX** [comment]
I don't use C#, but if I understand well, you are trying to mimic the command line arguments, right?

If you want to keep that way, what you must do is open both processes, connect the stdout of FFmpeg to the stding of the manager (which I understand you are doing here), and then configure FFmpeg to the equivalent parameters of ```-loop 1 -framerate 1```, so is FFmpeg who will keep looping over and over, sending the frames to the virtual camera, and you won't need the ```while(true)``` loop, so that way you will have one unique process for FFmpeg and one unique process for AkVCamManager. What i understand from your code is that you are launching the process every single loop.

Now, the best solution is no using FFmpeg, but instead using the C# API for reading the JPG, PNG, or whatever format (which I'm pretty sure C# has one, [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/0e079998-ffd8-4828-879b-9a09e7b8bc97/pass-from-jpeg-to-rgb-and-read-pixels?forum=csharpgeneral) is a possible solution), read the raw pixel data from the image, convert it to 24 bits RGB if necessary, then open the AkVCamManager, and keep sending the raw frames to the stdin in a loop, maybe using a clock or a sleep. So that way you just need one process and no more dependencies than the virtual camera. You can try adapting [the C example](https://github.com/webcamoid/akvirtualcamera/blob/master/share/examples/output_windows.c) to C#.

**Comment by hesa2020** [comment]
Hello thank you the function "GetRawBytes" from one of your link is what I needed.
Its working great but something weird is happening.
I am reading a jpg file that is supposed to be Bit depth 24.
I am creating a new Bitmap graphic and drawing my jpg onto it and then I convert that to raw bytes and stream it.
However the image has a blue tone to it as if it is missing a color channel.

Lets say it was RGB32 or ARGB32 instead of RGB24, wouldnt it be missing the Blue channel ?

**Comment by hipersayanX** [comment]
Good! sometimes can happen that the components red and blue are swapped, it depends on how the platform and the libraries define the format, if the arrangement depends on the byte endianness, if the stride is aligned or not, and many other things.

```
if (bmp.PixelFormat != PixelFormat.Format24bppRgb) throw new InvalidOperationException("Image format not supported.");
```

What you could do next is, instead of rejecting anything but Format24bppRgb, read the documentation to see which other formats are supported, and implement a proper reading/conversion function for that format.

```
for (int r = 0; r < h; ++r)
{
    for (int c = 0; c < rawStride; c += 3)
    {
        rawPtr[r * rawStride + c] = bmpPtr[r * bmpStride + c + 2];//red
        rawPtr[r * rawStride + c + 1] = bmpPtr[r * bmpStride + c + 1];//green
        rawPtr[r * rawStride + c + 2] = bmpPtr[r * bmpStride + c];//blue
    }
}
```

I would rather change that for this:

```
for (int y = 0; y < h; y++) {
    int offsetY = y * stride;

    int offsetRi = offsetY + 2;
    int offsetGi = offsetY + 1;
    int offsetBi = offsetY;

    int offsetRo = offsetY;
    int offsetGo = offsetY + 1;
    int offsetBo = offsetY + 2;

    for (int x = 0; x < rawStride; x += 3) {
        rawPtr[offsetRo + x] = bmpPtr[offsetRi + x]; // Red
        rawPtr[offsetGo + x] = bmpPtr[offsetGi + x]; // Green
        rawPtr[offsetBo + x] = bmpPtr[offsetBi + x]; // Blue
    }
}
```

The inner loop should always do just the bare minimum number of operations for speed, in graphics processing, the more operations you do, the bigger the penalty you get in the frame rate.
