### ISSUE TITLE
Wiki closed?

### ISSUE THREAD

**Issue by rnmp** [webcamoid/akvirtualcamera#6]
Hi! Let me know if I should recategorize this issue or post somewhere else instead.

https://github.com/webcamoid/akvirtualcamera/wiki

Seems to take you to the index of the repo. Presumably this is due to GitHub now charging for it?

Where can I find documentation?

**Comment by hipersayanX** [comment]
Only the members of the project can edit it, also there is not any documentation because I haven't finished testing it. What do you want to add to the wiki?

**Comment by rnmp** [comment]
Oh then nevermind. I was hoping to use this on a project I'm working on to generate a virtual camera stream on the background so I thought the wiki had some documentation on how to get started.

**Comment by hipersayanX** [comment]
I'll add the documentation once I finish debugging, testing and integrating with Webcamoid. But mean while you can install the driver and play with the AkVCamManager command line tool, also [here](https://github.com/webcamoid/akvirtualcamera/issues/3) are some examples. If you have any questions just ask me.

**Comment by cjbarth** [comment]
Is there something that I can do to help with that work?

**Comment by hipersayanX** [comment]
@cjbarth Right now, there are a lot of things to do:

*  Testing that the streaming and everything else is working fine in Webcamoid.
* Testing that you can properly set the default picture.
* Test that the installer is making a clean install/uninstall.
* Try to fix  #7
* Adding a --fps flag to regulate the stream.
* All previous for Windows and Mac.
* Write documentation.

That's all that comes to my head right now.
For now, since I've fixed some bugs with akvcam I'll use it as reference for polishing the code in Webcamoid and then I'll return to akvirtualcamera to finish wrapping up all the code.

**Comment by rnmp** [comment]
This work is greatly appreciated! Feel free to close my issue.

**Comment by hipersayanX** [comment]
Closing then :smiley:
