### ISSUE TITLE
Building the x32 version on Windows, and running akvCamManager

### ISSUE THREAD

**Issue by SeaSaltRay** [webcamoid/akvirtualcamera#73]
Choose one of the templates bellow that fit better your issue.

# Problem: Building the x32 version on Windows, and running akvCamManager

## Current Behavior

I followed the wiki instructions, and that was able to build an x64 version. However, I do not know how to make it build an x32 version. So, I continued on, hoping for some luck, and tried to create a new virtual camera, following the "configuring the cameras" guide. 

My command prompt returned the following message.
My input: AkVCamManager add-device -i vCam1 "Virtual Camera

Response: 'AkVCamManager' is not recognized as an internal or external command,
operable program or batch file.

If I click on the akvCamManager.exe in my folder view, a pop up appears staring this error: 

Line: 2017
Expression: string iterators incompatible (e.g. point to different string instances) 

## Expected Behavior

I would expect to be able to create a virtual camera

## Steps to Reproduce

1. Follow the wiki instructions for build and install, using Windows and Visual Studio
2. Build an x64 version, but not know how to build an x32 version
3. attempt to create a new virtual camera like so: AkVCamManager add-device -i vCam1 "Virtual Camera

## Suggestions and tips

I am assuming the error is with not having the x32 version, so it would be helpful to have an extra line in the wiki explaining the separate build processes.

## Your Environment

akvirtualcamera 9.1.1 (downloaded on 6/4/2024)
Working on a windows 10 pc

Attached is a screen shot of the error that appears if I try clicking on "AkVCamManager.exe"

![image](https://github.com/webcamoid/akvirtualcamera/assets/143825238/b9901a5e-eb03-4875-82cb-53c27fb704bf)

**Comment by hipersayanX** [comment]
Sorry for not answering before, I did labeled the issue then forget.

For compiling for booth architectures you can take a look at the build script I use for the github actions, either [using MSYS2](https://github.com/webcamoid/akvirtualcamera/blob/master/ports/ci/windows-msys/build.sh) or [Visual Studio](https://github.com/webcamoid/akvirtualcamera/blob/master/ports/ci/windows-vs/build.bat), you can adapt those scripts to your needs, the simplest build environment to use is MSYS2, VisualStudio can be a bit more complicated to setup.

>My command prompt returned the following message.
>My input: AkVCamManager add-device -i vCam1 "Virtual Camera
>
>Response: 'AkVCamManager' is not recognized as an internal or external command,
>operable program or batch file.

you must cd to the directory where is located the executable.

>If I click on the akvCamManager.exe in my folder view, a pop up appears staring this error:
>
>Line: 2017
>Expression: string iterators incompatible (e.g. point to different string instances)

AkVCamManager is a command line program it won't show any GUI, I'm not sure how you get that message and where is supposed to be pointing because at much, if you click it, it will open a console window and then close immediately.
Also, AkVCamManager must be run in a console with administrator privileges.

>so it would be helpful to have an extra line in the wiki explaining the separate build processes.

Is the same build process, just change the [toolset directory](https://github.com/webcamoid/akvirtualcamera/blob/851edfedff1efa5141946f590d1e0b33731a5524/ports/ci/windows-msys/build.sh#L40) (MSYS) or the [target architecture](https://github.com/webcamoid/akvirtualcamera/blob/851edfedff1efa5141946f590d1e0b33731a5524/ports/ci/windows-vs/build.bat#L33) (VisualStudio).

>Attached is a screen shot of the error that appears if I try clicking on "AkVCamManager.exe"

github doesn't show the image.

**Comment by TonyInTaiwan** [comment]
I would like to learn and build virtual driver like this, Following the build instructions , Downloaded MSYS2 and CMAKE, and then installed. 
Trying to compile  this code, yet it seems got some issues and I have no idea what going on.
May be I have to install something else. Therefore, would you please teach me . Could you ?

cmake -G "MSYS Makefiles" -S ..\cmio -B ..\cmio\Build
CMake Error: CMake was unable to find a build program corresponding to "MSYS Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_AR was not found, please set to archive program.
-- Configuring incomplete, errors occurred!

**Comment by hipersayanX** [comment]
@TonyInTaiwan

>May be I have to install something else.

[These](https://github.com/webcamoid/akvirtualcamera/blob/d149e99d1493ed21d7b10e6d91b86dfa25349c4f/.github/workflows/windows-msys.yml#L31) are the only dependencies required, you have the [github actions as a proof](https://github.com/webcamoid/akvirtualcamera/actions/workflows/windows-msys.yml).

```
cmake -G "MSYS Makefiles" -S ..\cmio -B ..\cmio\Build
CMake Error: CMake was unable to find a build program corresponding to "MSYS Makefiles". CMAKE_MAKE_PROGRAM is not set. You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_AR was not found, please set to archive program.
-- Configuring incomplete, errors occurred!
```

it sound like you forgot to set the [PATH variable](https://github.com/webcamoid/akvirtualcamera/blob/d149e99d1493ed21d7b10e6d91b86dfa25349c4f/ports/ci/windows-msys/build.sh#L61), .

Also, MSYS has different consoles for different [build environments](https://www.msys2.org/docs/environments/), in the action I'm using the [MSYS console](https://github.com/webcamoid/akvirtualcamera/blob/d149e99d1493ed21d7b10e6d91b86dfa25349c4f/.github/workflows/windows-msys.yml#L14), maybe that is what make the difference.
